<strong>Celler</strong><P>
	
Eldsj&auml;l &auml;r uppdelat i olika underavdelningar, celler. Dessa bildar
tillsammans det som kallas Eldsj&auml;l. I olika delar av sverige ser cellerna
och verksamheten ut p&aring; olika s&auml;tt. I de h&auml;r cellerna finns det
kontaktpersoner, det finns dock m&aring;nga andra delar av sverige d&auml;r det
h&auml;nder grejjer, s&aring; sl&auml;ng inte in handduken bara f&ouml;r att din stad inte st&aring;r
med h&auml;r!<P>

Kontaktpersoner<P>

Stockholm - <A HREF="userPresentation.asp?userId=2096" class=a2>ficklampa</A><BR>
&Ouml;stersund - <A HREF="userPresentation.asp?userId=1185" class=a2>tyllmeis</A><BR>
Norrk&ouml;ping - <A HREF="userPresentation.asp?userId=2802" class=a2>roots</A><BR>
J&ouml;nk&ouml;ping - <A HREF="userPresentation.asp?userId=2969" class=a2>sherlock</A><BR>
S&ouml;dert&auml;lje - <A HREF="userPresentation.asp?userId=3172" class=a2>alex.av.eld</A><BR>
Lidk&ouml;ping - <A HREF="userPresentation.asp?userId=2904" class=a2>gl&ouml;d</A><BR>
Landskrona - <A HREF="userPresentation.asp?userId=3540" class=a2>mirshann</A><BR>
Kalmar - <A HREF="userPresentation.asp?userId=2656" class=a2>tynnhammar</A>