<strong>Event</strong><P>
Eldsj&auml;l event sysslar med arrangemang av eldsj&auml;ls st&ouml;rre nationella tr&auml;ffar. De arrangerar bla. Ett av &aring;rets h&ouml;jdpunkter, Camp Burn Yourself, som arrangeras varje sommar. H&auml;r finns dessutom kompetens och st&ouml;d till andra medlemmar som vill arrangera evenemang.<P>

<A HREF="http://www.cby.se" class=a2 target="_new">www.cby.se</A><P>

Ansvarig: <A HREF="userPresentation.php?userId=787" class=a2>t</A>