<strong>Core</strong><P>
I eldsj&auml;l &auml;r det otroligt viktgt med den personilga anknytningen. Alla nya medlemmar f&aring;r en fadder som ber&auml;ttar hur eldsj&auml;l funkar, presenterar den nya medlemmen f&ouml;r nya m&auml;nniskor, svarar p&aring; fr&aring;gor osv.<P>

Att vara fadder &auml;r ett stort ansvar, hur en person upplever eldsj&auml;l kan till stor del vara beroende av faddern. D&auml;rf&ouml;r h&aring;ller eldsj&auml;l nu p&aring; att utveckla och driva ett system f&ouml;r att l&auml;ra och motivera faddrarna. Detta sysslar core med<P>

Ansvarig: <A HREF="userPresentation.php?userId=669" class=a2>krill</A>