<B>En s&auml;song i helvetet</B><P>

N&auml;r jag v&auml;nde mig till Juliet om att skriva f&ouml;r hennes underbara skapelse,
funderade jag p&aring; vad jag kunde g&ouml;ra eller s&auml;ga. Vad har jag egentligen att erbjuda mina med-eldare? Jag visste att jag ville dela med mig av vad jag l&auml;rt mig b&aring;de som artist och som individ. Juliet tog mig oundvikligen tillbaka till den vanligaste fr&aring;gan jag f&aring;tt de senaste m&aring;naderna, en fr&aring;ga jag fortfarande inte
besvarat till fullo: vad h&auml;nde?<BR>
Det &auml;r min utg&aring;ngspunkt.<BR>
Ist&auml;llet f&ouml;r att bara ge en f&ouml;rsmak ska jag blotta mig f&ouml;r er och ta er
med p&aring; en resa genom mitt psyke. Vi kommer tillsammans att uppleva vad som h&auml;nde
den d&auml;r &ouml;desdigra dagen och vilken typ av f&ouml;r&ouml;delse som kan tillfogas n&auml;r en av de
v&auml;rsta sortens olyckor intr&auml;ffar, sorten som f&aring;r en att tappa andan, och n&auml;stan f&ouml;rlora livet.<P>

Vi pausar en stund f&ouml;r en snabb introduktion. F&ouml;r de av er som inte k&auml;nner mig, &auml;r
jag Pele, en artist fr&aring;n nord&ouml;stra USA. Jag &auml;r k&auml;nd som den, tidvis, &ouml;verdrivet envisa
skribenten pÂ Home of Poi och &auml;ven forumens s&auml;kerhetspolis. Jag &auml;r en hoppfull kreativ
k&auml;lla och en h&auml;ngiven professionell artist. Jag har en passion f&ouml;r elden som mitt
element, och str&auml;var efter att hantera den s&auml;kert och skickligt, men med all
elegans och sk&ouml;nhet den besitter. Och den 20:e juli 2002 dog jag n&auml;stan f&ouml;r den passionen.<P>

Som de flesta av er vet &auml;r juli alltid en fullsp&auml;ckad m&aring;nad av upptr&auml;danden h&auml;r i
USA, och 2002 var det mest fullsp&auml;ckade &aring;ret f&ouml;r mig.
N&auml;r jag inte upptr&auml;dde, vilket jag verkade g&ouml;ra hela tiden, var jag upptagen med
koreografi, repetitioner, aff&auml;rsm&ouml;ten eller designing av utrustning till shower.
M&aring;naden i fr&aring;ga drabbades vi av den v&auml;rsta v&auml;rmeb&ouml;ljan och torkan vi
haft p&aring; flera &aring;r. Hettan, sistaminuten-ombyggnad av scenen p&aring; grund av den h&aring;rda
torra marken, och &auml;ndring av plats i sista minuten gjorde gr&auml;nsen mellan dag
och natt diffus. Detta var s&auml;rskilt p&aring;tagligt den 19:e juli. Min d&aring;varande
s&auml;kerhetsansvarige och hj&auml;lpreda i skapandet, Prometheus, gjorde sistaminuten-&auml;ndringar f&ouml;r att anpassa oss till den bruna gr&auml;st&auml;ckta vindh&auml;rjade &ouml;demark d&auml;r jag var bokad att
upptr&auml;da under 30 timmar de kommande fyra dagarna. Jag var fylld av of&ouml;rklarlig fasa och &aring;ngest.
Att jag lider av fruktansv&auml;rd scenskr&auml;ck &auml;r ingen hemlighet. Det sl&aring;r alltid till
ungef&auml;r en timme innan f&ouml;rest&auml;llningen. Jag skakar, ibland gr&aring;ter jag, f&aring;r knutar
i magen och &ouml;verv&auml;ger alla m&ouml;jliga s&auml;tt att slippa showen. Sen g&aring;r jag p&aring; och d&aring; k&auml;nns allt bra. Den h&auml;r g&aring;ngen slog &aring;ngesten till flera dagar tidigare &auml;n vanligt, med en
styrka som h&ouml;ll mig vaken om n&auml;tterna och gravt p&aring;verkade mitt psyke i dagar.<BR>
Oavsett hur upptagen jag var med annat, l&auml;mnade aldrig k&auml;nslan av fruktan mig.<BR>
Oavsett vad jag sysselsatte mig med f&ouml;rsvann fasan aldrig. Mitt f&ouml;rsta misstag
var att inte lyssna till den h&auml;r magk&auml;nslan.<P>

P&aring; onsdag den 20:e juli klockan 15.00 hade jag en sl&ouml; attityd d&aring; det var dags att upptr&auml;da,
vilket i normala fall inte &auml;r likt mig. Jag var kl&auml;dd i m&aring;nga lager Viktorianska
damunderkl&auml;der, inkluderande korsett och h&ouml;ga klackar pÂ en n&auml;stan 37 grader varm
dag. Prometheus pressade mig att vara redo i tid f&ouml;r att uppr&auml;tth&aring;lla den professionella
standard jag normalt stoltserar med. Solen var obarmh&auml;rtig och mitt scenutrymme bj&ouml;d
ingen skugga. Jag satte motstr&auml;vigt upp min schen, t&auml;nde tikifacklorna och betraktade
vad som skulle vara mitt "hem" f&ouml;r de kommande dagarna. De enda m&auml;nniskorna i n&auml;rheten var f&ouml;rs&auml;ljare, "st&aring;ndare", scenarbetare och en familj som &aring;t pommes frites vid ett picnicbord.<BR>
Vinden piskade genom mitt utrymme och slet ner kulissen &aring;tskilliga g&aring;nger. Vi var tvungna att justera, och &aring;ter justera p&aring; grund av detta. Det &auml;r d&aring; Dave, en av evenemangets organisat&ouml;rer kom f&ouml;rbi i sin golfbil. Han hade ett s&aring;nt d&auml;r diplomatiskt
s&auml;tt att se p&aring; sin klocka och sen artigt fr&aring;ga om allt var bra, och &aring;ter se p&aring; sin klocka och undra om allt skulle flyta p&aring; perfekt. Det sista han sade till mig n&auml;r
han k&ouml;rde iv&auml;g var: G&ouml;r v&auml;l ifr&aring;n dig men var s&auml;ker! Jag kommer ih&aring;g att jag ryckte p&aring;
axlarna n&auml;r han f&ouml;rsvann bakom en v&auml;gg av virvlande damm. Det var d&aring; jag, med en
djup suck, best&auml;mde mig f&ouml;r att t&auml;nda p&aring; och det &auml;r mitt andra misstag. Jag till&auml;t
min professionella stolthet bli f&ouml;rol&auml;mpad av en producent, tillr&auml;ckligt f&ouml;r att g&ouml;ra n&aring;gonting jag egentligen inte ville g&ouml;ra.<P>

Sedan f&ouml;ljer mitt tredje misstag, som jag inte ins&aring;g till fullo f&ouml;rr&auml;n jag skrev
den h&auml;r artikeln, men vilket var mitt absolut st&ouml;rsta. Som jag sagt tidigare var jag
k&auml;nd som s&auml;kerhetspolis. Jag lovar er alla, allt var d&auml;r fr&aring;n checklistan...
allt. Faktum &auml;r att, som f&ouml;rhalningsteknik kollade jag allting ca tio g&aring;nger. Mina
verktyg var s&auml;kra, fria fr&aring;n sot och redo att anv&auml;ndas. D&auml;r var ett nyligen p&aring;fyllt
f&ouml;rstahj&auml;lpen-kit, brandfilt, golvskydd av ull, brandsl&auml;ckare, massor av
extra v&auml;tska f&ouml;r att motverka uttorkning, fuktig handduk, s&auml;ker
br&auml;nsleavfallshink, s&auml;krad scen och en s&auml;kerhetsansvarig som kunde anv&auml;nda allt detta.
Vi hade allt, trodde jag. Nu vet jag att jag saknade den viktigaste
s&auml;kerhetsaspekten av dem alla. Jag respekterade inte det jag gjorde, och det &auml;r
den viktigaste s&auml;kerhetsproceduren. Jag kan komma p&aring; en miljon urs&auml;kter; hettan,
de l&aring;nga dagarna, den fasansfulla k&auml;nslan men vad det hela inskr&auml;nker sig till &auml;r
detta: jag hade gjort s&aring; m&aring;nga olycksfria shower att jag tog det f&ouml;r givet. Genom
att f&ouml;rlora respekten f&ouml;r elden, f&ouml;rlorade jag respekten f&ouml;r mig sj&auml;lv och min
konst. S&auml;kerhetsutrustningen &auml;r, i mina &ouml;gon, till f&ouml;r att skydda allt annat; min
respekt &auml;r det som skyddar mig. Jag hade blivit f&ouml;r bekv&auml;m med det jag gjorde
och f&ouml;rlorat min sk&auml;rpa. Jag s&auml;ger detta med starkaste m&ouml;jliga betoning, f&ouml;r sedan
min olycka har jag tr&auml;ffar p&aring; fler proffessionella artister som r&aring;kat ut f&ouml;r samma
sak. Vi kan tjata om s&auml;kerhetsfr&aring;gor hur mycket vi vill men i slut&auml;ndan, om du inte
startar med respekt, betyder alla dessa &aring;tg&auml;rder ingenting. Det var det st&ouml;rsta
misstaget jag gjorde.<P>

Vinden var brutal den dagen, v&auml;xlande mellan 0 och 50km/h. Det var s&aring; torrt att
damm och sm&aring;sten fl&ouml;g upp och stack i &ouml;gonen. N&auml;r jag &ouml;vade med mina poi och min
stav, f&aring;ngade vinden dem, vilket gjorde dem f&ouml;r sv&aring;ra att kontrollera trots deras
vikt. Jag spenderade en stor del av dagen med att vara uppm&auml;rksam p&aring; hur vinden
avtog och &ouml;kade, dess riktning och kraft. Hela dagen hade vinden varit &ouml;stlig. Jag
diskuterade mina m&ouml;jligheter med Prometheus, och jag l&auml;t min yrkesstolthet,
"the show must go on"-mentaliteten som bankats in i mig i &ouml;ver ett decennium, komma iv&auml;gen f&ouml;r mitt omd&ouml;me. Min magk&auml;nsla skrek &aring;t mig att bara l&auml;mna det h&auml;r. Missf&ouml;rst&aring;
mig inte nu, jag s&auml;ger inte att mitt misstag var att bl&aring;sa eld i bl&aring;st. Jag vet hur
farligt det kan vara. Jag &auml;r fullt medveten om, och utbildad i, riskerna. Jag har
bl&aring;st eld i m&aring;ttliga vindar fler g&aring;nger &auml;n jag kan minnas, n&aring;got jag inte rekommenderar
till n&aring;gon, men jag tar ansvar f&ouml;r mitt eget val. Mitt problem g&aring;r tillbaka till att
l&aring;ta min stolthet komma iv&auml;gen f&ouml;r att lyssna till mina instinkter, att inte
respektera elden eller mig sj&auml;lv tillr&auml;ckligt mycket f&ouml;r att l&auml;gga ner facklan och g&aring; d&auml;rifr&aring;n.<P>

Vinden hade mojnat till en smekande bris. Enligt mina tikifackell&aring;gor var den
fortfarande &ouml;stlig. Jag tog br&auml;nslet (lampolja, f&ouml;rresten) i min mun och satte
ig&aring;ng med mitt bl&aring;s. Det &auml;r h&auml;r rapporterna blir f&ouml;rvirrande. Jag har h&ouml;rt att jag
svalde br&auml;nsle, inhalerade eld, det har varit m&aring;nga olika redog&ouml;relser. Det h&auml;r
&auml;r vad som h&auml;nde. Jag lyckades med en eldpelare, vilket var mitt m&aring;l. Som en del
av er kanske vet, d&aring; man bl&aring;ser en stark eldpelare st&auml;ts br&auml;nslet ut i en lite j&auml;mnare
str&ouml;m vilket inneb&auml;r att medan eldpelaren h&aring;ller, matar artisten fortfarande pelaren med mer aspirerat br&auml;nsle. Det var d&aring; vinden v&auml;nde. Jag hade just slutat bl&aring;sa ut br&auml;nslet.
Jag backade, torkade av munnen och inhalerade genom n&auml;san. Vinden tilltog inte bara,
utan &auml;ndrade samtidigt riktning till v&auml;stlig. Eldpelaren passerade ovanf&ouml;r mitt huvud.
Ist&auml;llet f&ouml;r att ant&auml;nda, bl&aring;ste &aring;terstoden av det aspirerade br&auml;nslet tillbaka i mitt
ansikte d&aring; jag andades in, och gick upp i min n&auml;sa och ner i mina lungor. Hela den h&auml;r
historien str&auml;cker sig &ouml;ver ca 15 minuter. Olyckan tog mindre &auml;n en sekund och jag
visste omedelbart att jag hade f&aring;tt problem.<P>

Jag kippade efter luft och ropade &aring;t Prometheus att h&auml;mta vattenflaskan
och pillerna med aktivt kol. Mina bih&aring;lor br&auml;nde. Min hals blev omedelbart torr. Du
vet hur man i actionfilmer kan se folk ta emot ett knytn&auml;vsslag i br&ouml;stet, och man
tappar andan sj&auml;lv n&auml;r man f&ouml;rest&auml;ller sig sm&auml;rtan? Det k&auml;ndes som att det var vad
som h&auml;nde med mitt br&ouml;st, men byt ut tr&auml;ffen mot en br&auml;nnande k&auml;nsla. Jag duckade
bakom kulissen och b&ouml;rjade hosta s&aring; intensivt att jag inte fick luft.<BR>
Sedan b&ouml;rjade kr&auml;kningarna. Jag slet i sn&ouml;rningen i min kostym, det k&auml;ndes som att den
h&ouml;ll mig fast som i ett skruvst&auml;d. Jag visste att detta kunde h&auml;nda, jag trodde bara
aldrig att det skulle g&ouml;ra det. Jag visste vad som var fel men stackars Prometheus,
han unders&ouml;kte mig och var n&auml;stan panikslagen.<P>

Efter ca tre minuter bad jag dem att ringa 911. Jag var p&aring; sjukhuset min dre &auml;n 15
minuter efter olyckan. Jag fick syrgas, gav sarkastiska svar &aring;t &ouml;verfl&ouml;det av
fr&aring;gor och trodde verkligen att jag skulle bli bra och att jag skulle vara
tillbaka p&aring; jobbet n&auml;sta dag. Jag tvivlade aldrig p&aring; min f&ouml;rm&aring;ga att slutf&ouml;ra
showen. Vi tog med oss br&auml;nsleflaskan, sjukhuset r&ouml;ntgade mitt br&ouml;st och gjorde
giftkontroller. Det var h&auml;r jag var outbildad, och det &auml;r mitt sista misstag. Jag
var inte medveten om mina patientr&auml;ttigheter, ej heller k&auml;nde jag till de
rekommenderade behandlingarna f&ouml;r br&auml;nsleinhalering. Jag visste att vid sv&auml;ljning
fylls magen med kol som pumpas ut igen. Detta var nytt territorium f&ouml;r mig.<BR>
R&ouml;ntgenpl&aring;tarna visade att mina lungor var fria fr&aring;n v&auml;tska och skador. Jag hade
allts&aring; inhalerat s&aring; lite att det inte ens syntes! F&ouml;ga visste jag att jag
borde f&aring;tt bronkvidgande medel, fuktigt syre, antibiotika och f&ouml;rmodligen
magpumpats ocks&aring;. Giftavdelningen sade &aring;t akuten att beh&aring;lla mig. Jag k&auml;nde mig
inte bekv&auml;m med att &aring;ka hem. De skrev ut mig, fast jag sa att jag inte ville det.<BR>
Jag hade andats in br&auml;nsle, vad som f&aring;r n&aring;gon att tro att det &auml;r okej kan jag inte
f&ouml;rst&aring;, men jag &aring;kte d&auml;rifr&aring;n. Mitt misstag var att inte k&auml;nna till de r&auml;tta
behandlingsmetoderna, protokoll och patientr&auml;ttigheter.<P>

Det &auml;r standardiserad sjukhusrutin att patienter f&aring;r en lista &ouml;ver symptom att vara
uppm&auml;rksamma p&aring; d&aring; de skrivs ut, och instruktioner att Âterv&auml;nda till sjukhuset
om de k&auml;nner av n&aring;gra av dem. Min lista bestod av "allvarliga" former av
n&aring;gon av f&ouml;ljande: feber, svullen eller &ouml;m hals, andningsbesv&auml;r, sv&aring;righeter att
&auml;ta, br&ouml;stsm&auml;rtor, och kr&auml;kningar. Runt klockan ett p&aring; natten uppvisade jag l&auml;tta
tecken pÂ flera av dessa. Klockan sex p&aring; morgonen var Prometheus n&auml;stan tvungen
att b&auml;ra mig tillbaka till akuten, inte ens 12 timmar sedan sist. N&auml;rmare br&ouml;str&ouml;ntgen
visade en del skador p&aring; b&aring;da lungorna samt att de uts&ouml;ndrade v&auml;tska och h&ouml;ll p&aring; att
fyllas. Jag skrevs in, fick syre och drogades. Saker b&ouml;rjar bli diffusa f&ouml;r mig
efter det. Den lokala andningsspecialisten ber&auml;ttade att han inte kunde hantera
mitt fall och att sjukhuset jag befann mig p&aring; inte var utrustat f&ouml;r s&aring;dana h&auml;r incidenter.
Jag var tvungen att f&ouml;rflyttas och var v&auml;ldigt uppr&ouml;rd &ouml;ver det. Jag minns att jag
vaknade i ambulansen under f&ouml;rflyttningen. Genom en drogframkallad dimma sÂg jag en
man sv&auml;va &ouml;ver mitt ansikte. Jag ins&aring;g att d&auml;r var n&aring;gonting i min mun (senare
uppt&auml;ckte jag att det var en intubation) men en nerdrogad flicka p&aring; rygg t&auml;nker
inte mycket p&aring; killen ovanf&ouml;r henne med n&aring;gonting ned i hennes hals s&aring; jag f&ouml;rs&ouml;kte
kl&aring; upp honom. N&auml;sta sak jag minns &auml;r tre veckor senare. Jag vaknade och min mor
h&ouml;ll min hand. Det s&auml;gs att jag vaknat och gr&aring;tit under denna treveckorsperiod,
men jag var tungt s&ouml;vd s&aring; jag minns ingenting av det. Intubationen drogs ur min hals,
och ist&auml;llet utf&ouml;rdes en trakeotomi. Genom h&aring;let i min hals fick jag fuktigt syre
pumpat direkt in i lungorna (f&ouml;r att hindra sekretet fr&aring;n att stelna), och det till&auml;t
sk&ouml;terskorna att sticka ner ett sugr&ouml;r i mina lungor och reng&ouml;ra dem. En sm&auml;rta och
k&auml;nsla som inte g&aring;r att beskriva. Min feber pendlade mellan 41 och 42 grader, vilket
var deras fr&auml;msta bekymmer och kamp fr&aring;n dag till dag. Jag hade f&aring;tt
bukspottk&ouml;rtelsinflammation, vilket fortfarande &auml;r of&ouml;rklarat. Jag fick &auml;ven
urinv&auml;gsinfektion p.g.a. katetern. Jag fick ber&auml;ttat att jag varit n&auml;ra att d&ouml; tv&aring;
g&aring;nger. Jag hade varken r&ouml;st eller f&ouml;rm&aring;ga att tala p.g.a. trakeotomituben. Jag
kunde knappt r&ouml;ra mina h&auml;nder, &auml;nnu mindre sitta upp eller g&aring;. Jag fick varken &auml;ta
eller dricka. Jag var inte ens stark nog f&ouml;r att gr&aring;ta. Jag s&aring;g ut som Doctor
Octopus fr&aring;n serierna p.g.a. alla r&ouml;r i mig. Jag k&auml;nde mig som en f&aring;nge i min egen
kropp, frustrerad, arg, s&aring;rad och, trots str&ouml;mmen av bes&ouml;kare, v&auml;ldigt ensam. Det
var det sv&aring;raste jag n&aring;gonsin f&aring;tt utst&aring;, mentalt, fysiskt och k&auml;nslom&auml;ssigt...
vilket s&auml;ger en hel del med tanke p&aring; att jag &auml;ven &auml;r ensamst&aring;ende mor.<P>

Under ytterligare tv&aring; veckor var jag v&auml;ldigt flitig i mitt tillfrisknande.
Jag s&aring;g mycket pÂ TV, s&aring;g sommaren passera i all sin prakt utan mig, och det
st&ouml;rde mig varenda minut. De tv&aring; veckorna verkade vara en evighet. Jag var tvungen
att samla min styrka f&ouml;r att l&auml;ra mig att g&aring; igen. Jag f&ouml;rlorade 9 kg bara
muskler eftersom de f&ouml;rtvinade. Jag fick l&auml;ra mig att sv&auml;lja igen, att koncentrera
mig p&aring; att trycka v&auml;tska eller mat f&ouml;rbi min trakea, och jag misslyckades fatalt
p&aring; f&ouml;rsta f&ouml;rs&ouml;ket. Och andas... det &auml;r fortfarande inte s&aring; l&auml;tt f&ouml;r mig. Att l&auml;ra
sig g&ouml;ra n&aring;gonting som tidigare varit s&aring; automatiskt, som jag aldrig f&ouml;rr beh&ouml;vt
l&auml;ra mig var sv&aring;rt. P&aring; regelbunden basis v&auml;cktes jag av ljudet av mekaniska sirener
fr&aring;n maskinerna jag var kopplad till, med sk&ouml;terskor sv&auml;vandes ovanf&ouml;r mig,
p&aring;minnandes mig om att komma ih&aring;g att andas, att ta ett djupt andetag.<BR>
Att f&aring; ig&aring;ng kroppens minne var den st&ouml;rsta utmaningen. Jag l&auml;rde k&auml;nna personalen
v&auml;ldigt v&auml;l, men inte s&aring; intimt som de k&auml;nde mig. Det var pinsamt och f&ouml;rnedrande,
trots det faktum att de var uppmuntrande, st&ouml;ttande och gjorde det s&aring; l&auml;tt f&ouml;r mig
som de bara kunde.<P>

Jag har fortfarande &auml;rret &ouml;ver min hals, 15cm brett och ca 4cm h&ouml;gt. En
daglig p&aring;minnelse att beh&aring;lla den d&auml;r respekten, att vara uppm&auml;rksam p&aring; mina
instinkter, att utbilda mig sj&auml;lv l&aring;ngt mer &auml;n vad jag trodde jag beh&ouml;vde, att inte
l&aring;ta min stolthet komma iv&auml;gen. Det kommer ta ett tag innan jag &auml;r fullt frisk.
Min undre v&auml;nstra lunga har ca 10% permanent &auml;rrv&auml;vnad. Min styrka, uth&aring;llighet
och kropp m&aring;ste &aring;ter jobbas upp. F&ouml;r var dag blir jag friskare. Ibland gl&ouml;mmer jag
att jag skadat mig, och anstr&auml;nger mig lite f&ouml;r mycket. Ibland k&auml;nner jag att full
fart inte &auml;r fort nog.<P>

I slut&auml;ndan delar jag med mig av detta med hoppet att &aring;tminstone en av er kommer att dra
f&ouml;rdel av min upplevelse. Allt jag kan g&ouml;ra efter att ha ber&auml;ttat denna hemska
ber&auml;ttelse &auml;r att &aring;ter styrka de punkter jag k&auml;nner starkast f&ouml;r.<P>

1. Lyssna till dina instinkter. Om jag hade lyssnat till mina, hade det h&auml;r
troligen inte h&auml;nt.<P>

2. Producenter, managers och organisat&ouml;rer f&ouml;rst&aring;r inte fullt ut vad vi g&ouml;r. De &auml;r
d&auml;r f&ouml;r att tj&auml;na pengar, precis som vi. St&aring; upp mot dem. Du kan bibeh&aring;lla
professionalitet utan att &auml;ventyra din h&auml;lsa.<P>

3. K&auml;nn till dina patientr&auml;ttigheter och ha din f&ouml;rs&auml;kring i ordning. Efter min
sjukhusvistelse var f&ouml;rs&auml;kringskampen sv&aring;r. K&auml;nn till vilka behandlingar som kr&auml;vs
f&ouml;r alla m&ouml;jliga omst&auml;ndigheter du SKULLE KUNNA r&aring;ka ut f&ouml;r. Var medveten om att
det inte handlar om "om", utan "n&auml;r" det h&auml;nder. K&auml;nn till vilka behandlingsmetoder som kr&auml;vs f&ouml;r:
Alla typer av utv&auml;rtes br&auml;nnskador, br&auml;nsleskador/utslag, br&auml;nslef&ouml;rgiftning,
kemisk lunginflammation, r&ouml;kinhalering och inv&auml;rtes br&auml;nnskador.
B&auml;r med dig en beskrivning av dessa i ditt f&ouml;rsta hj&auml;lpen kit.<P>

4. Respekt. Jag kan inte betona detta nog. Utan respekt &auml;r alla andra
s&auml;kerhets&aring;tg&auml;rder meningsl&ouml;sa. Respektera dig sj&auml;lv, din publik och elden. Bli
inte f&ouml;r bekv&auml;m med elden. Tro aldrig att det inte kan h&auml;nda dig.<P>

Dessa &auml;r bara f&ouml;rslag, mina v&auml;nner, riktlinjer du kanske vill t&auml;nka p&aring; innan din
n&auml;sta show, och alla kommande shower.<P>

De senaste m&aring;naderna har jag h&ouml;rt "stackars Pele" m&aring;nga g&aring;nger. Sn&auml;lla, tyck inte
synd om mig, f&ouml;r p&aring; m&aring;nga s&auml;tt &auml;r jag lyckligt lottad. Jag &auml;r vid liv och inser nu
till fullo vilken g&aring;va livet &aring;r. I efterhand &auml;r jag glad att den h&auml;r olyckan
h&auml;nde mig ist&auml;llet f&ouml;r n&aring;gon av er underbara m&auml;nniskor. Jag &auml;r berikad av
erfarenheten. Jag &auml;r starkare. Jag &auml;r visare. Jag har f&ouml;rnyat fokus och passion f&ouml;r
mitt yrke. Jag &auml;r inte arg eller uppr&ouml;rd, och jag &auml;r inte l&auml;ngre f&ouml;rvirrad
kring varf&ouml;r olyckan skedde.<P>

Tack f&ouml;r att du tagit denna k&auml;nslom&auml;ssiga, om &auml;n korta resa med mig. F&ouml;r mig
har det varit renande att uttrycka termerna och k&auml;nslorna kring min olycka f&ouml;r
andra som &auml;r lika passionerade f&ouml;r den h&auml;r konstformen som jag &auml;r. Genom att &aring;terber&auml;tta
detta f&ouml;r er hoppas jag att, varje g&aring;ng ni t&auml;nder p&aring; eller intar scenen, n&aring;gonting
jag skrivit kommer f&ouml;lja med er, resonera inuti er, f&aring;r er att ta det d&auml;r
extra andetaget f&ouml;r ett &ouml;gonblick. F&ouml;rhoppningsvis kommer jag en dag att vara i er publik,
appl&aring;derandes och hejandes med folket. Och m&ouml;jligen, i en idealframtid, kommer vi ta
det d&auml;r andetaget tillsammans, inte bara som artister men ocks&aring; som en st&ouml;ttande
artistisk gemenskap. Till dess mina v&auml;nner &ouml;nskar jag er alla h&auml;lsa, s&auml;kerhet och djupa friska andetag.<P>



<I>Texten &auml;r &ouml;versatt med tillst&aring;nd fr&aring;n f&ouml;rfattaren Pelé.<BR>
Tack till incendo f&ouml;r &ouml;vers&auml;ttningen.</I>
