<B>F&ouml;reningen eldsj&auml;ls f&ouml;rs&auml;kring</B><P>

Om v&aring;r F&ouml;rs&auml;kring.<P>

Vi i eldsj&auml;l har beslutat att f&ouml;rs&auml;kra oss hos L&auml;nsf&ouml;rs&auml;kringar AB, och kommer mot ers&auml;ttning erbjudas en m&auml;ngd f&ouml;rdelar vi skada osv, som jag redovisar nedan.<P>

&#167;1) Ansvarsf&ouml;rs&auml;kring<br/>
G&auml;ller vid skadest&aring;ndskrav f&ouml;r sak och personskada som uppst&aring;tt till f&ouml;ljd av den f&ouml;rs&auml;krade verksamheten eller genom skadebringande egenskaper i f&ouml;reningens produkter. sj&auml;lvrisk 7860kr.<P>

(detta inneb&auml;r att om vi br&auml;nner ner n&aring;tt eller n&aring;gon s&aring; betalar LF v&aring;ra r&auml;tteg&aring;ngskostnader och ers&auml;tter vedeb&ouml;rande.)<P>

&#167;2) R&auml;ttskyddsf&ouml;rs&auml;kring<br/>
g&auml;ller f&ouml;r r&auml;tteg&aring;ngskostnader i m&aring;l som ber&ouml;r den f&ouml;rs&auml;krade verksamheten innom norden.<P>

(dom betalar r&auml;tteg&aring;ngskostnadet som &ouml;verstiger 19 650 och d&auml;refter 80% av kostnaderna.)<P>

&#167;3) kollektiv olycksfallsf&ouml;rs&auml;kring<br/>
F&ouml;rs&auml;kringsbolaget t&auml;cker v&aring;ra kostnader vid olycksfall.<P>

(Vissa special grejer h&auml;r.. den g&auml;ller INTE f&ouml;r capoiera eller annan kampsport, och den g&auml;ller bara i Norden (och tillf&auml;lliga semestrar som inte &ouml;verstiger 3 m&aring;naders boende i resten av v&auml;rlden). Den m&aring;ste s&auml;gas upp minst en m&aring;nad innan den ska avslutas, annars f&ouml;rts&auml;tter den ett &aring;r till. )<P>

(d&ouml;r eller handikappas en medlem p&aring; grund av atomk&auml;rnproccess (k&auml;rnvapen) s&aring; f&aring;r denne 200 000 kr.)<P>

L&auml;karrelaterade kostnader t&auml;cks (sk&auml;liga och n&ouml;dv&auml;ndiga kostnader).<br/>
Vid inplantat exempelvis nya t&auml;nder t&auml;cker den upp till 9825 kr.<br/>
Kl&auml;der, glas&ouml;gon, utrustning osv t&auml;cks upp till 9825 kr.<br/>
&Auml;rr och &auml;rrbildning ers&auml;tts (sk&auml;liga och n&ouml;dv&auml;ndiga kostnader).<br/>
ivaliditet f&ouml;rs&auml;kras f&ouml;r mellan 196 500 - 786 000 :-<br/>
d&ouml;r en medlem s&aring; f&aring;r dennes kvarlevande 19 650kr.
