<B>Uteslutande av medlem</B><P>

Innan varje varning utdelas, ska en dialog f&ouml;rs&ouml;ka etableras med personen i fr&aring;ga. Denne ska f&aring; en m&ouml;jlighet att f&ouml;rklara sitt handlande och varf&ouml;r den har brutit mot regel/stadgar. Man ska alltid efterstr&auml;va att ha en verklig kontakt med personen i fr&aring;ga, alternativt prata per telefon. Detta ska s&auml;rskilt beaktas d&aring; risk f&ouml;r missf&ouml;rst&aring;nd f&ouml;religger.<P>

Ifall den som ska dela ut varningen riskerar att inte ha en objektiv st&auml;llning, tex. pga. en personlig relation till personen i fr&aring;ga, ska en annan styrelsemedlem ta hand om &auml;rendet.<P>

#1<br/>
Vem som helst i styrelsen kan utdela den f&ouml;rsta varningen. Varningen ska delas ut som ett meddelande, Innh&aring;llande f&ouml;ljande.<P>

Information om att personen har f&aring;tt en varning<br/>
H&auml;nvsining till detta dokumen(l&auml;nk)<br/>
Information om en specifik h&auml;ndelse, f&ouml;r vilken varningen &auml;r utdelad, med citat om det g&auml;ller n&aring;gonting skrivet.<br/>
H&auml;nvisning till n&aring;got policydokument eller annat av styrelsen god&auml;knt dokument (s&aring; som "ordning och reda"-brevet eller stadgar) i vilket praxis som medlemen brutit n&auml;ms,
Information om att tre varningar medf&ouml;r en uteslutning fr&aring;n communityn eldsj&auml;l.<P>

Ingenting mer ska finnas med i meddeandet.<P>

#2<br/>
F&ouml;r varning nummer tv&aring; kr&auml;vs ett majoritetsbeslut fr&aring;n stryelsen, detta sker l&auml;mpligen i styrelsekorrespondansen, eller p&aring; ett styrelsem&ouml;te.<P>

inf&ouml;r omr&ouml;stningen ska f&ouml;ljande information delges alla styrelsemedlemmar:<br/>
Information om en specifik h&auml;ndelse, f&ouml;r vilken varningen &auml;r utdelad, med citat om det g&auml;ller n&aring;gonting skrivet.<P>

H&auml;nvisning till n&aring;got policydokument eller annat av styrelsen god&auml;knt dokument (s&aring; som "ordning och reda"-brevet eller stadgar) i vilket praxis som medlemen brutit n&auml;ms.<P>

Varningen ska delas ut som ett meddelande, innh&aring;llande f&ouml;ljande.<P>

Information om att personen har f&aring;tt sin andra varning<br/>
H&auml;nvsining till detta dokumen(l&auml;nk)<br/>
Information om en specifik h&auml;ndelse, f&ouml;r vilken varningen &auml;r utdelad, med citat om det g&auml;ller n&aring;gonting skrivet.<br/>
H&auml;nvisning till n&aring;got policydokument eller annat av styrelsen god&auml;knt dokument (s&aring; som "ordning och reda"-brevet eller stadgar) i vilket praxis som medlemen brutit n&auml;ms,
Information om att tre varningar medf&ouml;r en uteslutning fr&aring;n communityn eldsj&auml;l.<P>

Ingenting mer ska finnas med i meddeandet.<P>

#3<br/>
Varning nummer tre inneb&auml;r ocks&aring; ett uteslutande ifr&aring;n eldsj&auml;ls community.<P>

F&ouml;r varning nummer tre kr&auml;vs ett majoritetsbeslut fr&aring;n stryelsen, detta sker l&auml;mpligen i styrelsekorrespondansen, eller p&aring; ett styrelsem&ouml;te.<P>

inf&ouml;r omr&ouml;stningen ska f&ouml;ljande information delges alla styrelsemedlemmar:<P>
Information om en specifik h&auml;ndelse, f&ouml;r vilken varningen &auml;r utdelad, med citat om det g&auml;ller n&aring;gonting skrivet.<P>

H&auml;nvisning till n&aring;got policydokument eller annat av styrelsen god&auml;knt dokument (s&aring; som "ordning och reda"-brevet eller stadgar) i vilket praxis som medlemen brutit n&auml;ms.<P>

Varningen ska delas ut som ett e-post meddelande, innh&aring;llande f&ouml;ljande.<P>

Information om att personen har f&aring;tt sin tredje varning<br/>
H&auml;nvsining till detta dokumen(l&auml;nk)<br/>
Information om en specifik h&auml;ndelse, f&ouml;r vilken varningen &auml;r utdelad, med citat om det g&auml;ller n&aring;gonting skrivet.<br/>
H&auml;nvisning till n&aring;got policydokument eller annat av styrelsen god&auml;knt dokument (s&aring; som "ordning och reda"-brevet eller stadgar) i vilket praxis som medlemen brutit n&auml;ms<br/>
information om huruvida personen i framtiden kan g&ouml;ra en ny ans&ouml;kning om medlemskap p&aring; eldsjal.org (ett &aring;r)<br/>
Information om att tre varningar medf&ouml;r en uteslutning fr&aring;n communityn eldsj&auml;l.<P>

Ingenting mer ska finnas med i meddeandet.<P>

Anser en eldsj&auml;l att en annan eldsj&auml;l b&ouml;r uteslutas fr&aring;n communityn, skall detta meddelas till styrelsen via kontaktformul&auml;ret p&aring; eldsjal.org, med f&ouml;ljande information:<P>

Information om en specifik h&auml;ndelse, f&ouml;r vilken varningen &auml;r utdelad, med citat om det g&auml;ller n&aring;gonting skrivet.<br/>
H&auml;nvisning till n&aring;got policydokument eller annat av styrelsen god&auml;knt dokument (s&aring; som "ordning och reda"-brevet eller stadgar) i vilket praxis som medlemen brutit n&auml;ms.