<strong>Stadgar f&ouml;r f&ouml;reningen Eldsj&auml;l</strong><P>

<strong>&#167;1. Namn</strong><br/>
F&ouml;reningens namn &auml;r Eldsj&auml;l.<P>

<strong>&#167;2. Form</strong><br/>
Eldsj&auml;l &auml;r en ideell f&ouml;rening. Eldsj&auml;l st&aring;r sj&auml;lvst&auml;ndig gentemot stater,
kommuner, religi&ouml;sa, politiska och privata intressen. F&ouml;reningens s&auml;te &auml;r
i Stockholm.<P>

<strong>&#167;3. Syfte och m&aring;ls&auml;ttning</strong><br/>
Eldsj&auml;l &auml;r en &ouml;ppen f&ouml;rening.<br/>
F&ouml;reningen skall st&ouml;dja och uppmuntra medlemmarnas kulturella och sociala
engagemang. F&ouml;reningen skall ocks&aring; verka f&ouml;r att medlemmarna, genom
kunskaps- och erfarenhetsutbyte, har m&ouml;jlighet att utvecklas kreativt och
socialt.<br/>
En stor del av Eldsj&auml;ls arbete fokuserar p&aring; gatuteater, konst, hantverk,
nycirkus, teater och musik i alla dess former.<br/>
Eldsj&auml;l skall vara &ouml;ppen f&ouml;r nya konstformer och s&auml;tt f&ouml;r individer att
uttrycka sig, samt fr&auml;mja ett samh&auml;lle d&auml;r detta &auml;r m&ouml;jligt.<br/>
Eldsj&auml;l arbetar aktivt f&ouml;r att motverka fr&auml;mlingsfientlighet,
diskriminering samt mobbing av alla dess slag.<br/>
Eldsj&auml;l arbetar f&ouml;r att fr&auml;mja direktdemokrati.<P>

<strong>&#167;4. Medlemskap</strong><br/>
F&ouml;reningen &auml;r &ouml;ppen f&ouml;r alla fysiska personer. Medlem &auml;r den som betalt
medlemsavgift. Medlem har r&auml;tt till full insyn i verksamheten,
n&auml;rvarande-, yttrande- och f&ouml;rslagsr&auml;tt p&aring; alla m&ouml;ten. Medlem har r&ouml;str&auml;tt
p&aring; medlems- och &aring;rsm&ouml;te. Medlem ansvarar f&ouml;r att verka i enlighet med Eldsj&auml;ls
m&aring;ls&auml;ttning och uppfyller de av Eldsj&auml;l stadgade kraven.<br/>
Medlem uppmuntras att engagera sig i m&ouml;ten och att utveckla f&ouml;reningen.<br/>
Medlem ansvarar ocks&aring; f&ouml;r att f&ouml;lja alla policydokument.<P>

<strong>&#167;5. Kommunikation</strong><br/>
Intern kommunikation i f&ouml;reningen sker genom elektronisk media.<br/>
F&ouml;reningens plattform &auml;r http://www.eldsjal.org.<br/>
Alla kallelser, policydokument, protokoll samt motioner skall finnas
tillg&auml;ngliga f&ouml;r medlemmar via plattformen eller e-post, medlem ansvarar
f&ouml;r att ta del av dessa. Motioner skall publiceras p&aring; plattformen minst 24 timmar
innan medlems- eller &aring;rsm&ouml;te.<P>

<strong>&#167;6. M&ouml;ten</strong><br/>
Medlemsm&ouml;te behandlar propositioner, motioner och f&ouml;rslag. Medlemsm&ouml;te
skall utlysas minst 72 timmar i f&ouml;rv&auml;g
Alla medlemmar kan utlysa ett medlemsm&ouml;te.<br/>
&Aring;rsm&ouml;te skall utlysas minst 14 dagar i f&ouml;rv&auml;g av styrelsen och skall
behandla f&ouml;ljande:<br/>
- verksamhetsber&auml;ttelse<br/>
- bokslut<br/>
- ansvarsfrihet f&ouml;r avg&aring;ende styrelse<br/>
- val av ny styrelse<br/>
- val av revisor<br/>
- fastst&auml;llande av medlemsavgift<br/>
- propositioner, motioner och f&ouml;rslag<br/>
- val av valberedning som skall best&aring; av 3 fysiska personer.<br/>
Vid alla m&ouml;ten skall en majoritet av styrelsen n&auml;rvara f&ouml;r att m&ouml;tet skall
vara giltigt. &Aring;rsm&ouml;te skall h&aring;llas senast juni m&aring;nad.<P>

<strong>&#167;7. Styrelse</strong><br/>
Styrelsen beslutar &ouml;ver l&ouml;pande fr&aring;gor och &auml;r underst&auml;lld medlems- och
&aring;rsm&ouml;te. En majoritet av styrelsen m&aring;ste n&auml;rvara f&ouml;r att styrelsen skall vara
beslutsm&auml;ssig. Styrelsen skall str&auml;va efter konsensusbeslut, vid oenighet
g&auml;ller enkel majoritet. Styrelsem&ouml;te skall h&aring;llas minst tre g&aring;nger per &aring;r.<br/>
Styrelsen skall best&aring; av 7 - 11 ordinarie ledam&ouml;ter. Styrelsen
konstituerar sig sj&auml;lva med undantag av ordf&ouml;rande och kass&ouml;r som v&auml;ljs
vid &aring;rsm&ouml;te.<br/>
Nya ers&auml;ttare f&ouml;r styrelsemedlemmar v&auml;ljs vid medlemsm&ouml;te.<P>

<strong>&#167;8. Firmatecknare</strong><br/>
Firmatecknare f&ouml;r f&ouml;reningen Eldsj&auml;l &auml;r nuvarande Ordf&ouml;rande och Kass&ouml;r.<P>

<strong>&#167;9. Verksamhets&aring;r</strong><br/>
F&ouml;reningens verksamhets&aring;r l&ouml;per fr&aring;n f&ouml;rsta januari till sista december.<P>

<strong>&#167;10. Uteslutning</strong><br/>
Medlem som klart bryter mot Eldsj&auml;ls stadgar, kan av styrelsen uteslutas.<br/>
Den uteslutne har r&auml;tt att &ouml;verklaga beslutet vid
medlemsm&ouml;te d&auml;r den uteslutne har r&ouml;str&auml;tt. Styrelsen f&ouml;rbeh&aring;ller sig
r&auml;tten att direkt utesluta medlem som, i Eldsj&auml;ls namn, beg&aring;r lagbrott.<P>

<strong>&#167;11. Omr&ouml;stning</strong><br/>
Vid &aring;rs- och medlemsm&ouml;te g&auml;ller f&ouml;ljande:<br/>
- Vid beslut skall konsensus efterstr&auml;vas.<br/>
- Vid lika r&ouml;stetal avg&ouml;r ordf&ouml;randes r&ouml;st. Vid lika r&ouml;stetal i personval
sker omr&ouml;stning mellan de tv&aring; starkaste kandidaterna, om majoritet ej
erh&aring;lles sker lottning.<P>

<strong>&#167;12. Stadge&auml;ndring</strong><br/>
F&ouml;r att &auml;ndra dessa stadgar kr&auml;vs 2/3 majoritet vid tv&aring; p&aring; varandra
f&ouml;ljande medlemsm&ouml;ten varav ett &aring;rsm&ouml;te och tr&auml;der i kraft d&auml;refter.<P>

<strong>&#167;13. Uppl&ouml;sning</strong><br/>
F&ouml;reningens uppl&ouml;sning beslutas med minst 2/3 majoritet vid tre p&aring;
varandra f&ouml;ljande medlemsm&ouml;ten varav ett &aring;rsm&ouml;te. Efter revisorernas
godk&auml;nnande av r&auml;kenskaperna skall tillg&aring;ngarna f&ouml;rdelas till
organisationer eller f&ouml;reningar med liknande m&aring;ls&auml;ttning. Det sista m&ouml;tet
beslutar om f&ouml;rdelning av medel.