<?php
$application = array(
	'userhistory'=>6,
	'systemnewsitems'=>2,
	'newsadmin'=>6,
	'systemforumcount'=>6,
	'newsadmin'=>6,
	'forumadmin'=>6,
	'linksadmin'=>3,
	'calendaradmin'=>3,
	'imageadmin'=>3,
	'wisdomadmin'=>3,
	'useradmin'=>2,
	'triviaadmin'=>2,
	'admin'=>10,
	'eldsjalDB'=>'omgwtf',
	'lastUpdate'=>'imorgon',
	'version'=>'2&frac12;',
	'versionname'=>'<a href="http://en.wikipedia.org/wiki/Mad_Hatter">Mad hatter</a> release',
	'loggedincount'=>'J&auml;ttem&aring;nga',
	'membercount'=>'Miljoners miljarders',
	'visitorcount'=>'En hel del',
	'originalimagepath'=>'../originalImages',
	'calendarimagepath'=>'../uploads/calendar',
	'newsimagepath'=>'../uploads/news',
	'galleryimagepath' => '../uploads/galleryImages',
	'userimagepath'=>'../uploads/userImages',
	'imagepath'=>'../upload',
	'userimageuri' => '/uploads/userImages/',
	'ripuser' => 1590
);